import time
import logging

from opentelemetry import trace
from app.services.rag.history_and_cache import _save_to_history

# Set up tracing
tracer = trace.get_tracer(__name__)

# Set up logging
logger = logging.getLogger(__name__)


async def _handle_greeting(query, chat_id, user, proj, sectors, start_time, greeting_response=None):
    """
    Handle greeting queries.
    
    Args:
        query: Original user query
        chat_id: Chat session ID
        user: User object
        proj: Project ID
        sectors: List of sectors
        start_time: Pipeline start time
        greeting_response: Pre-generated greeting response from query processor (optional)
    
    Returns:
        Dict with greeting response and metadata
    """
    
    # If greeting_response already generated by query processor, use it
    if greeting_response:
        logger.info(f"[GREETING] Using pre-generated response from query processor")
        greeting_text = greeting_response
    else:
        # Fallback: Generate greeting response here (shouldn't happen with new flow)
        logger.warning(f"[GREETING] Generating fallback response (query processor didn't provide one)")
        greeting_text = "Hello! I'm your Compliance Assistant. How can I help you with banking, compliance, or regulatory queries today?"
    
    # Save to history
    await _save_to_history(chat_id, user.user_id, query, proj, sectors, greeting_text)
    
    # Calculate processing time
    processing_time = time.time() - start_time
    
    logger.info(f"[GREETING] Handled in {processing_time*1000:.0f}ms")
    
    return {
        "result": greeting_text, 
        "source_documents": [], 
        "is_comparative": False, 
        "model_used": "router_0.5B_smart_greeting",
        "processing_time": processing_time,
        "from_cache": False,
        "is_greeting": True 
    }